name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request:
    branches: [master]
    # sync = update
    types: [opened, synchronize] 

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  # PreDeploymentChecks:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3 # Checksout the latest commit in your repo.
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "16"
  #     - name: npm install
  #       run: npm install
  #     - name: lint
  #       run: npm run eslint
  #     - name: build
  #       run: npm run build
  #     - name: test
  #       run: npm run test
  #     - name: e2e tests
  #       uses: cypress-io/github-action@v2
  #       with:
  #         command: npm run test:e2e
  #         start: npm run start-prod
  #         wait-on: http://localhost:5000
  DelpoyToFlyio:
    if: ${{ github.event_name == 'push' }}
    # needs: [PreDeploymentChecks]
    runs-on: ubuntu-20.04
    steps:
      # - name: Deployment
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: '0'
      # - uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: flyctl deploy --remote-only
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          WITH_V: true
          DRY_RUN: true

